Local
HappyR0b0t/password_generator pull request #2
Opened 2023-07-10 22:16 UTC by HappyR0b0t

Переделал коммиты, так чтобы действительно отображалось, то, что предлагается к ревью.

2023-07-11 13:45 UTC, homm requested changes

2023-07-11 13:45 UTC, homm commented on .vscode/settings.json
> +{
Это персональные настройки, они не относятся напрямую к проекту. Нужно сначала удалить файл, потом добавить его в .gitignore.

2023-07-11 13:45 UTC, homm commented on password_generator_v2.0.py
> password_generator_v2.0.py

Версию не стоит добавлять в название файла

2023-07-11 13:45 UTC, homm commented on password_generator_v2.0.py
> +main()
Сейчас эта строчка `main()` выполнится при любом использовании этого модуля, как при запуске `password_generator_v2.0.py`, так и при импорте из другого кода `import password_generator_v2.0.py`.

Чтобы код выполнялся только при запуске используют такую конструкцию:
```suggestion
if __name__ == '__main__':
    main()
```

2023-07-11 13:45 UTC, homm commented on password_generator_v2.0.py
> +def pwd_generator(PWD_LENGTH):
Заглавными пишут только константы. В данном случае это параметр

```suggestion
def pwd_generator(pwd_length):
```

2023-07-11 13:45 UTC, homm commented on password_generator_v2.0.py
> +        PWD_LENGTH = input("Enter a desired character count: ")
Тут тоже строчными имя переменной

2023-07-11 13:45 UTC, homm commented on password_generator_v2.0.py
> +    alphabet = letters + digits + special_chars
Эти переменные нигде не используются отдельно, так что можно сократить.

```suggestion
    similar_characters = 'il1Lo0O'
    ambigous_chars = '{}[\\]()/\'"`~,;:.<>|'
    alphabet = string.ascii_letters + string.digits + string.punctuation
```

2023-07-11 13:45 UTC, homm commented on password_generator_v2.0.py
> +    PWD = ''
Тут тоже самое с регистром переменных

2023-07-11 13:45 UTC, homm commented on password_generator_v2.0.py
> +def exclusion_choice(m, chars):
Зачем тут принимать `m`? Она не используется

2023-07-11 13:45 UTC, homm commented on password_generator_v2.0.py
> +            m = str(m)
Здесь `m` и так будет строка, так что во-первых это преобразование не нужно. Во-вторых никогда не вызовет `ValueError`.

2023-07-11 13:45 UTC, homm commented on password_generator_v2.0.py
> +        PWD += ''.join(secrets.choice(alphabet))
Тут не используется `i`, обычно ненужную переменную называют `_`.

```suggestion
    for _ in range(PWD_LENGTH):
        PWD += ''.join(secrets.choice(alphabet))
```

Для чего тут нужен `''.join()`?

2023-07-11 13:45 UTC, homm commented on password_generator_v2.0.py
> +    print(PWD)
Лучше когда функция делает одно действие, например генерирует пароль по заданным параметрам. В данном случае функция сама спрашивает у пользователя параметры и выводит результат на экран, откуда его уже никуда не достать. Было бы лучше вынести этот функционал из непосредственной функции генерации:

```python
exclude_similar = exclusion_choice('similar')
exclude_ambigous = exclusion_choice('ambigous')
pwd = pwd_generator(char_count(), exclude_similar, exclude_ambigous)
print("Your password is:", pwd)
```

2023-07-12 09:29 UTC, homm approved these changes

2023-07-12 09:29 UTC, homm commented on .gitignore
> +# .vscode/
Все что начинается с # это комментарий, оно не учитывается

2023-07-12 09:29 UTC, homm commented on password_generator.py
> +            continue
В данном случае это и так будет continue

2023-07-12 09:29 UTC, homm commented on password_generator.py
> +    return pwd
Вопрос стиля, можно упростить до одной строки:

```suggestion
    return ''.join(secrets.choice(alphabet) for _ in range(pwd_length))
```

2023-07-12 09:29 UTC, homm commented on password_generator.py
> +    if excl_chars is True:
```suggestion
    if exclusion_choice(chars):
```

2023-07-12 09:29 UTC, homm commented on password_generator.py
> +        char_exclusion(char_exclusion(alphabet, similar_chars), ambigous_chars)
Тут всё корректно, но я бы оставил в несколько строк для лучшей читаемости:

```python
alphabet = char_exclusion(alphabet, similar_chars)
alphabet = char_exclusion(alphabet, ambigous_chars)
```

2023-07-12 11:54 UTC, HappyR0b0t commented on .gitignore
> +# .vscode/
Да, забыл раскомментировать (

2023-07-12 12:59 UTC, HappyR0b0t commented on password_generator.py
> +        char_exclusion(char_exclusion(alphabet, similar_chars), ambigous_chars)
Вот тут я не понимаю, как сделать.
Мне нужно два раза вызвать `char_exclusion`, а передать `alphabet` в pwd- один раз.
Внутри pwd у меня не получается поочередно присвоить alphabet новое значение, пишет - keyword argument repeated. Т.е. вот такое не работает у меня:

`def main():
    pwd = pwd_generator(
        char_count(),
        alphabet = char_exclusion(alphabet, ambigous_chars),
        alphabet = char_exclusion(alphabet, similar_chars)
    )
    print("Your password is: ", pwd)`

Если помещу вызов `char_exclusion` перед pwd, то работать будет неправильно, да и пишет, что переменная упомянута ранее ее назначения.

2023-07-13 09:22 UTC, homm commented on password_generator.py
> +        char_exclusion(char_exclusion(alphabet, similar_chars), ambigous_chars)
Точно, понял о чем ты. Да, если переменная глобальная, то так написать нельзя:

```python
def main():
    alphabet = char_exclusion(alphabet, similar_chars)
    alphabet = char_exclusion(alphabet, ambigous_chars)
```

Потому что с точки зрения питона все переменные, которые ты хоть раз присваиваешь внутри функции, являются локальными и он просто не видит тут глобальную `alphabet`, поэтому и пишет, что переменная упомянута ранее ее назначения.

## Вариант неправильный

Можно добавить global.

```python
def main():
    global alphabet
    alphabet = char_exclusion(alphabet, similar_chars)
    alphabet = char_exclusion(alphabet, ambigous_chars)
```

Тогда питон увидит глобальную переменную alphabet, но и присваивать будет ей же. То есть каждый вызов main просто будет затирать изначальную alphabet.

## Вариант 1

Использовать другое имя:

```python
def main():
    chars = char_exclusion(alphabet, similar_chars)
    chars = char_exclusion(chars, ambigous_chars)
```

Тут нет присваивания `alphabet`, поэтому она глобальная, а `chars` будет локальной.

## Вариант 2

Принимать алфавит как параметр, при этому сделать ему значение по-умолчанию:

```python
def main(alphabet=alphabet):
    alphabet = char_exclusion(alphabet, similar_chars)
    alphabet = char_exclusion(alphabet, ambigous_chars)
```

Тут как ни странно `alphabet` будет локальной переменной (параметры тоже локальные переменные), но значение этой локальной переменной объявлено как глобальная  `alphabet`.

2023-07-13 09:30 UTC, HappyR0b0t commented on password_generator.py
> +        char_exclusion(char_exclusion(alphabet, similar_chars), ambigous_chars)
А вот такое будет сильно кринжово?

```
def main():
    pwd = pwd_generator(
        char_count(),
        char_exclusion(alphabet)
    )
    print("Your password is: ", pwd)
    ```
    ```
    def char_exclusion(alphabet):
    def exclusion(alphabet, chars):
        if exclusion_choice(chars):
            for i in chars:
                alphabet = alphabet.replace(i, '')
        return alphabet

    alphabet = exclusion(alphabet, similar_chars)
    alphabet = exclusion(alphabet, ambigous_chars)
    return alphabet
    ```

2023-07-13 09:35 UTC, HappyR0b0t commented on password_generator.py
> +        char_exclusion(char_exclusion(alphabet, similar_chars), ambigous_chars)
Вот это выглядит элегантно, надо попробовать
``` python
def main(alphabet=alphabet):
    alphabet = char_exclusion(alphabet, similar_chars)
    alphabet = char_exclusion(alphabet, ambigous_chars)
```

2023-07-13 10:16 UTC, homm approved these changes
Идеально )

2023-07-13 10:49 UTC, merged